version: '3.9'

services:
  application:
    build: .
    container_name: hotel-api
    command: sh -c "dockerize -wait tcp://rabbitmq:5672 -timeout 60s -wait-retry-interval 5s npm run start:dev"
    ports:
      - 3333:3333
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - appnet

  mysql:
    image: mariadb:10.5.8
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: hotel
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge